Repository elementary/appcenter, pull requests merged in 2018-09, with the labels that each got.

#788 Use threads to prevent UI from blocking on Pk operations
  src/Views/AppInfoView.vala
  src/Widgets/AppContainers/AbstractAppContainer.vala
Labels: Priority: High

#803 Add title to StripeDialog
  src/Dialogs/StripeDialog.vala
Labels: Bitesize

#804 Add null check to fix #784
  src/Widgets/AppContainers/AbstractAppContainer.vala
Labels: Bitesize

#806 AppData: Remove .desktop from app ID
  data/io.elementary.appcenter.appdata.xml.in
Labels: Bitesize

#810 Handle Explicit Content
  data/io.elementary.appcenter.gschema.xml
  src/Core/Package.vala
  src/Dialogs/ContentWarningDialog.vala
  src/Settings.vala
  src/Widgets/AppContainers/AbstractAppContainer.vala
  src/Widgets/Banner.vala
  src/Widgets/Carousel/Carousel.vala
  src/meson.build
Labels: Priority: Critical

#820 Fix blacklist path
  src/Core/ComponentValidator.vala
Labels: Bitesize

#816 Better bounds checking in get_newest_releases
  src/Core/Package.vala
Labels: Priority: High
