Repository elementary/appcenter, pull requests merged in 2019-10, with the labels that each got.

#1092 flatpak: Work with user-specific flatpaks by default
  src/Core/FlatpakBackend.vala
Labels: Bitesize

#1096 CategoryFlowBox: use correct icon for office category
  src/Widgets/CategoryFlowBox.vala
Labels: Bitesize

#1109 AbstractAppContainer: Also check for os_updates in install_approved
  src/Widgets/AppContainers/AbstractAppContainer.vala
Labels: Bitesize, Priority: High

#1110 Release 3.2.0
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release
