Repository elementary/appcenter, pull requests merged in 2020-10, with the labels that each got.

#1401 Release 3.5.0
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release

#1429 Release 3.5.1
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Bitesize, Release

#1437 AppData: Fix a typo "beeen" to "been"
  data/io.elementary.appcenter.appdata.xml.in
Labels: Bitesize
