Repository elementary/appcenter, pull requests merged in 2020-06, with the labels that each got.

#1350 Rewrite ScreenshotCache
  src/Core/Client.vala
  src/Core/ScreenshotCache.vala
  src/Views/AppInfoView.vala
Labels: Priority: High

#1358 Simplify substring calculations for component
  src/Core/BackendAggregator.vala
  src/Core/Package.vala
Labels: Bitesize

#1359 Exclude Flatpak runtimes from package pool
  data/io.elementary.appcenter.appdata.xml.in
  src/Core/ComponentValidator.vala
  src/Core/FlatpakBackend.vala
Labels: Priority: High

#1376 Release 3.4.1
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release
