Repository elementary/appcenter, pull requests merged in 2021-09, with the labels that each got.

#1647 Banner: tweak copy
  src/Widgets/Banner.vala
Labels: Bitesize

#1629 StripeDialog: move pay-what-you-can flow here
  data/icons/categories.gresource.xml
  data/icons/currency-dollar-symbolic.svg
  data/styles/banner.css
  po/POTFILES
  src/Dialogs/StripeDialog.vala
  src/Views/AppInfoView.vala
  src/Widgets/AppContainers/AbstractAppContainer.vala
  src/Widgets/HumbleButton.vala
  src/Widgets/HumblePopover.vala
  src/meson.build
Labels: Needs Design

#1668 AppInfoView: fix content warning wrap
  src/Views/AppInfoView.vala
Labels: Bitesize

#1675 AppInfoView: Remove oars_header
  src/Views/AppInfoView.vala
Labels: Bitesize

#1677 Homepage: Fix building with homepage=false
  src/Views/Homepage.vala
Labels: Bitesize

#1683 AppInfoView: Show an icon for uncurated apps
  src/Views/AppInfoView.vala
Labels: Needs Copy

#1684 Change OARS icons namespace
  data/icons/categories.gresource.xml
  src/Views/AppInfoView.vala
Labels: Bitesize

#1687 AppInfoView: only show non-curated badge when using `curated` flag
  src/Views/AppInfoView.vala
Labels: Bitesize

#1689 AppInfoView: Prevent focusing OARS ContentTypes
  src/Views/AppInfoView.vala
Labels: Bitesize

#1696 AppInfoView: disable non-curated badge on OS updates
  src/Views/AppInfoView.vala
Labels: Bitesize
