Repository elementary/appcenter, pull requests merged in 2021-08, with the labels that each got.

#1566 Release 3.6.1
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release

#1570 Package: Fix gettext syntax
  src/Core/Package.vala
Labels: Bitesize, i18n

#1569 MainWindow: Show Open only when a desktop app is installed
  src/MainWindow.vala
Labels: Bitesize

#1579 AppInfoView: Don't try to update size info in case of local packages
  src/Views/AppInfoView.vala
Labels: Bitesize

#1577 AbstractPackageRowGrid: Remove changed signal to InstalledPackageRowGrid
  src/Widgets/AppContainers/AbstractPackageRowGrid.vala
  src/Widgets/AppContainers/InstalledPackageRowGrid.vala
  src/Widgets/PackageRow.vala
Labels: Bitesize

#1582 Release 3.6.2
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release

#1594 Package: unescape name
  src/Core/Package.vala
  src/Views/AppInfoView.vala
  src/Widgets/AppContainers/AbstractAppContainer.vala
  src/Widgets/AppContainers/AbstractPackageRowGrid.vala
  src/Widgets/PackageRow.vala
Labels: Bitesize

#1591 AbstractAppContainer: Remove is_os_updates property
  src/Widgets/AppContainers/AbstractAppContainer.vala
  src/Widgets/PackageRow.vala
Labels: Bitesize

#1592 AbstractAppContainer: Reduce variable scope
  src/Widgets/AppContainers/AbstractAppContainer.vala
Labels: Bitesize

#1599 Release 3.6.3
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release

#1619 Banner: reduce method scope
  src/Widgets/Banner.vala
Labels: Bitesize

#1617 Banner: on_any_color_change → reload_css
  src/Widgets/Banner.vala
Labels: Bitesize

#1625 Appdata: add release data for 3.7.0
  data/io.elementary.appcenter.appdata.xml.in
Labels: Bitesize

#1639 Release 3.7.1
  data/io.elementary.appcenter.appdata.xml.in
  meson.build
Labels: Release
