Repository elementary/appcenter, pull requests merged in 2021-07, with the labels that each got.

#1542 AppInfoView: Fix truncated footer links
  src/Views/AppInfoView.vala
Labels: Bitesize

#1552 Release 3.6.0
  data/io.elementary.appcenter.appdata.xml.in
  data/screenshot-footer.png
  data/screenshot-updates.png
  data/screenshot.png
  meson.build
Labels: Release

#1561 Gresource symbolic mail icon
  data/icons/categories.gresource.xml
  data/icons/internet-mail-symbolic.svg
  data/io.elementary.appcenter.appdata.xml.in
Labels: Bitesize

#1567 LINGUAS: Add Panjabi and sort
  po/LINGUAS
  po/extra/LINGUAS
Labels: Bitesize, i18n
